#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server
# Function to display usage
display_usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

# Check if number of parameters is less than 4
if [ "$#" -lt 4 ]; then
    display_usage
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer file using scp with StrictHostKeyChecking disabled
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~

echo "File transferred successfully to $username@$server_ip:~/"

