#!/usr/bin/env bash
# Bash script that configures an Ubuntu server
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "facebook.com 8.8.8.8" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
